2024-10-17 00:57:44.219954-03:00 jdbc[97]: exception
org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-224]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:690)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1425)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:314)
	at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:337)
	at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java)
	at io.getquill.context.jdbc.JdbcContextVerbExecute.executeAction$$anonfun$1(JdbcContextVerbExecute.scala:38)
	at io.getquill.context.qzio.ZioJdbcUnderlyingContext.withConnectionWrapped$$anonfun$1$$anonfun$1$$anonfun$1(ZioJdbcUnderlyingContext.scala:98)
	at io.getquill.context.qzio.ZioJdbcUnderlyingContext.sqlEffect$$anonfun$1(ZioJdbcUnderlyingContext.scala:102)
	at zio.ZIOCompanionVersionSpecific.attempt$$anonfun$1(ZIOCompanionVersionSpecific.scala:103)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:990)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:999)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:971)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1066)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:999)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1066)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1066)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:999)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1066)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1066)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:999)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:971)
	at zio.internal.FiberRuntime.evaluateEffect(FiberRuntime.scala:361)
	at zio.internal.FiberRuntime.evaluateMessageWhileSuspended(FiberRuntime.scala:435)
	at zio.internal.FiberRuntime.drainQueueOnCurrentThread(FiberRuntime.scala:207)
	at zio.internal.FiberRuntime.run(FiberRuntime.scala:134)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
2024-10-17 00:57:44.220453-03:00 jdbc[96]: exception
org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-224]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:690)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1425)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:314)
	at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:337)
	at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java)
	at io.getquill.context.jdbc.JdbcContextVerbExecute.executeAction$$anonfun$1(JdbcContextVerbExecute.scala:38)
	at io.getquill.context.qzio.ZioJdbcUnderlyingContext.withConnectionWrapped$$anonfun$1$$anonfun$1$$anonfun$1(ZioJdbcUnderlyingContext.scala:98)
	at io.getquill.context.qzio.ZioJdbcUnderlyingContext.sqlEffect$$anonfun$1(ZioJdbcUnderlyingContext.scala:102)
	at zio.ZIOCompanionVersionSpecific.attempt$$anonfun$1(ZIOCompanionVersionSpecific.scala:103)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:990)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:999)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:971)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1066)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:999)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1066)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1066)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:999)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1066)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1066)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:999)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:971)
	at zio.internal.FiberRuntime.evaluateEffect(FiberRuntime.scala:361)
	at zio.internal.FiberRuntime.evaluateMessageWhileSuspended(FiberRuntime.scala:435)
	at zio.internal.FiberRuntime.drainQueueOnCurrentThread(FiberRuntime.scala:207)
	at zio.internal.FiberRuntime.run(FiberRuntime.scala:134)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
2024-10-17 00:57:44.220330-03:00 jdbc[93]: exception
org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-224]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:690)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1425)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:314)
	at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:337)
	at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java)
	at io.getquill.context.jdbc.JdbcContextVerbExecute.executeAction$$anonfun$1(JdbcContextVerbExecute.scala:38)
	at io.getquill.context.qzio.ZioJdbcUnderlyingContext.withConnectionWrapped$$anonfun$1$$anonfun$1$$anonfun$1(ZioJdbcUnderlyingContext.scala:98)
	at io.getquill.context.qzio.ZioJdbcUnderlyingContext.sqlEffect$$anonfun$1(ZioJdbcUnderlyingContext.scala:102)
	at zio.ZIOCompanionVersionSpecific.attempt$$anonfun$1(ZIOCompanionVersionSpecific.scala:103)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:990)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:999)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:971)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1066)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:999)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1066)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1066)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:999)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1066)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1066)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:999)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:971)
	at zio.internal.FiberRuntime.evaluateEffect(FiberRuntime.scala:361)
	at zio.internal.FiberRuntime.evaluateMessageWhileSuspended(FiberRuntime.scala:435)
	at zio.internal.FiberRuntime.drainQueueOnCurrentThread(FiberRuntime.scala:207)
	at zio.internal.FiberRuntime.run(FiberRuntime.scala:134)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
2024-10-17 00:57:44.288336-03:00 jdbc[97]: exception
org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-224]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:690)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1425)
	at org.h2.jdbc.JdbcConnection.clearWarnings(JdbcConnection.java:660)
	at com.zaxxer.hikari.pool.ProxyConnection.close(ProxyConnection.java:267)
	at io.getquill.context.ZioJdbc$.scopedBestEffort$$anonfun$2$$anonfun$1(ZioJdbc.scala:146)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at zio.ZIOCompanionVersionSpecific.attempt$$anonfun$1(ZIOCompanionVersionSpecific.scala:103)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:990)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:999)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:999)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:999)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:999)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1135)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:971)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:971)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:971)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:971)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:999)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1135)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:971)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:971)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:971)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:999)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1066)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1066)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:999)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:971)
	at zio.internal.FiberRuntime.evaluateEffect(FiberRuntime.scala:361)
	at zio.internal.FiberRuntime.evaluateMessageWhileSuspended(FiberRuntime.scala:435)
	at zio.internal.FiberRuntime.drainQueueOnCurrentThread(FiberRuntime.scala:207)
	at zio.internal.FiberRuntime.run(FiberRuntime.scala:134)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
2024-10-17 00:57:44.289064-03:00 jdbc[96]: exception
org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-224]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:690)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1425)
	at org.h2.jdbc.JdbcConnection.clearWarnings(JdbcConnection.java:660)
	at com.zaxxer.hikari.pool.ProxyConnection.close(ProxyConnection.java:267)
	at io.getquill.context.ZioJdbc$.scopedBestEffort$$anonfun$2$$anonfun$1(ZioJdbc.scala:146)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at zio.ZIOCompanionVersionSpecific.attempt$$anonfun$1(ZIOCompanionVersionSpecific.scala:103)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:990)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:999)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:999)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:999)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:999)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1135)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:971)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:971)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:971)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:971)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:999)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1135)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:971)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:971)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:971)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:999)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1066)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1066)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:999)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:971)
	at zio.internal.FiberRuntime.evaluateEffect(FiberRuntime.scala:361)
	at zio.internal.FiberRuntime.evaluateMessageWhileSuspended(FiberRuntime.scala:435)
	at zio.internal.FiberRuntime.drainQueueOnCurrentThread(FiberRuntime.scala:207)
	at zio.internal.FiberRuntime.run(FiberRuntime.scala:134)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
2024-10-17 00:57:44.288393-03:00 jdbc[93]: exception
org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-224]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:690)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1425)
	at org.h2.jdbc.JdbcConnection.clearWarnings(JdbcConnection.java:660)
	at com.zaxxer.hikari.pool.ProxyConnection.close(ProxyConnection.java:267)
	at io.getquill.context.ZioJdbc$.scopedBestEffort$$anonfun$2$$anonfun$1(ZioJdbc.scala:146)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at zio.ZIOCompanionVersionSpecific.attempt$$anonfun$1(ZIOCompanionVersionSpecific.scala:103)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:990)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:999)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:999)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:999)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:999)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1135)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:971)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:971)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:971)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:971)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:999)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1135)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:971)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:971)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:971)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:999)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1066)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:1066)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:999)
	at zio.internal.FiberRuntime.runLoop(FiberRuntime.scala:971)
	at zio.internal.FiberRuntime.evaluateEffect(FiberRuntime.scala:361)
	at zio.internal.FiberRuntime.evaluateMessageWhileSuspended(FiberRuntime.scala:435)
	at zio.internal.FiberRuntime.drainQueueOnCurrentThread(FiberRuntime.scala:207)
	at zio.internal.FiberRuntime.run(FiberRuntime.scala:134)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
